system:
  domain: webSite
  version: 1.0
  env: "dev"
  HttpPort: ":5001"
  Host: "localhost"
  UploadModel: "local"

mysql:
    dialect: "mysql"
    dbHost: "127.0.0.1"
    dbPort: "3306"
    dbName: "mall_db"
    userName: "mall"
    password: "123456"
    charset: "utf8mb4"

redis:
  redisDbName: 4
  redisHost: 127.0.0.1
  redisPort: 6379
  redisPassword: 123456
  redisNetwork: "tcp"