system:
  domain: webSite
  version: 1.0
  AppEnv: "release"
  HttpPort: ":5001"
  Host: "localhost"
  UploadModel: "local"
  Jwt: "dwfyaxxccc"


mysql:
  dbHost: "database-cd-test.cswacuhfujiz.eu-west-1.rds.amazonaws.com"
  dbPort: "3306"
  dbName: "db_wynpay"
  userName: "cddev"
  password: "k08yc5by5e63"
  charset: "utf8mb4"


redis:
  redisDbName: 6
  redisHost: "114.117.164.200"
  redisPort: 6379
  redisPassword: qwe1230.
  redisNetwork: "tcp"

rongcloud:
  appkey: "sfci50a7sjlmi"
  appsecret: "D9dS1g1U3BU9"
  defaultPhoto: "formal/avatar.png"
