definitions:
  request.FormationMode:
    properties:
      currency_code:
        type: string
      utm_campaign:
        type: string
      utm_medium:
        type: string
      utm_source:
        type: string
    type: object
  request.UserLogin:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  response.ResData:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
      time:
        type: integer
    type: object
info:
  contact: {}
  description: wynpay
  title: Gin-Server Swagger API接口文档
  version: v0.0.1
paths:
  /api/formation/v1/save:
    post:
      consumes:
      - application/json
      description: 保存连接信息并生成连接
      parameters:
      - description: phone,password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.FormationMode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResData'
      summary: SaveFormation
      tags:
      - SaveFormation 保存连接信息并生成连接
  /api/user/v1/login:
    post:
      consumes:
      - application/json
      description: 帐号登陆
      parameters:
      - description: phone,password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ResData'
      summary: Login
      tags:
      - Login 帐号登陆
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
